#ifndef LEDMATRIXPICTUREDATABASETYPES_HPP
#define LEDMATRIXPICTUREDATABASETYPES_HPP

enum LEDMatrixPictureDataBaseTypes{
    LED_MATRIX_NO_TYPE,
    LED_MATRIX_PICTURE,
    LED_MATRIX_PICTURE_ELEMENT,
    NUMB_OF_LED_MATRIX_PICTURE_DATA_BASE_TYPES
};

#endif // LEDMATRIXPICTUREDATABASETYPES_HPP
