#ifndef LEDMATRIXPICTUREELEMENTTYPES_HPP
#define LEDMATRIXPICTUREELEMENTTYPES_HPP

enum LEDMatrixPictureElementTypes{
    LED_MATRIX_PICTURE_ELEMENT_NO_TYPE, // ERROR
    LED_MATRIX_PICTURE_ELEMENT_TYPE_RECT,
    LED_MATRIX_PICTURE_ELEMENT_TYPE_LED_MATRIX,
    NUMB_OF_LED_MATRIX_PICTURE_ELEMENT_TYPES
};

#endif // LEDMATRIXPICTUREELEMENTTYPES_HPP
